### ISSUE TITLE
Pure code

### ISSUE THREAD

**Issue by Tibing** [ZloiY/akveo_todolist#5]
I believe you've heard about pure code. So, it is a fairy tail :blush:
But you need to seek to write pure code. And I think [this book](https://www.bsuir.by/m/12_100229_1_98218.pdf) can help you.

For now, you need to resolve second problems:
- Global variables. Programs shouldn't have global variables.
- All function and variables should have eloquent names. So that by name the content was clear. (Remove all one letter vars)
- One function - one thing. So you need to split your functions into many small functions which do its job. 
- And of course, you need to clean all nesting in ![your code](https://cloud.githubusercontent.com/assets/17410089/26090578/89c83704-3a0e-11e7-9c42-29691899375b.png). Let's agree you will not create more than 3 level nesting block

**Comment by ZloiY** [comment]
Solve problems with variables.
